runtime: python39
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  # IMPORTANT: Replace the placeholder below with your actual API key 
  GEMINI_API_KEY: "AIzaSyAiLkPKq92BWm7wPruOkGE6fqx5JFjOvNA"
